### ISSUE TITLE
July updates sensors stop to work 

### ISSUE THREAD

**Issue by jesterino** [AlgorithmicEntropy/SolarWattHassio#12] opened 2024-07-21 12:27 UTC
Hello
With last update of ha
2024.7.3
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240710.0
No sensor are available 
It need some update ?

**Comment by AlgorithmicEntropy** [comment] 2024-07-24 11:41
It is still working on my installation:
Core: 2024.7.3
Supervisor: 2024.06.2
Operating System: 12.4
Can you maybe check your logs under System -> Logs?

**Comment by AlgorithmicEntropy** [comment] 2024-08-24 11:00
Issue was caused by an update of the energy manager firmware, should be fixed in the next release

**Closed** 2024-08-24 11:28 UTC
